Player:
	Color: 88F865

Game:
	Mod: ts

Sound:

Graphics:

Server:
	AllowPortForward: False
	Map: 294002f10fe55e802740bf3d4bd81488374fd968

Debug:
	SystemInformationVersionPrompt: 1
	UUID: 89d320dd-4702-48e0-8e1e-3ce81776fc5d
	LuaDebug:true
	PerfText:true
	PerfGraph:true

Keys:

Chat:

